# Generated by Django 3.0.6 on 2020-06-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('idade', models.CharField(blank=True, default='', max_length=3)),
                ('telefone', models.CharField(blank=True, default='', max_length=13)),
                ('endereco', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
